version: '3.9'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    networks:
      - php-app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - php-app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo_password
      MYSQL_DATABASE: demo_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - php-app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: demo_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - php-app-network

networks:
  php-app-network:

volumes:
  mysql_data:

